class_name SimRace
extends RefCounted
# One round's race. The live player is simulated tick by tick from input
# bytes; ghosts are position streams regenerated by re-simulating their
# recorded input logs against the level as it stood when they were
# recorded. Fates (which ghost dies to which newer hazard, and when) are
# precomputed at setup so resolution is deterministic and skippable.

const RESOLVE_BEAT := 40          # ticks of quiet after the last resolution

var level: SimLevel
var tracks: Array = []            # arrow tracks {t0, life, x0, y, dir, round}
var p: SimPlayer
var tick: int = 0
var inputs := PackedByteArray()   # the live run's input log (the replay)
var ghost_streams: Array = []     # {xs, ys, faces, len, finished}
var fates: Array = []             # {death: tick or -1, done: tick}
var cushion_last := {}             # item index -> last trigger tick
var events: Array = []            # drained by the shell each tick; cosmetic

static func create(all_items: Array, roster: Array, template: SimLevel = null) -> SimRace:
	var base := template if template != null else SimLevel.build([])
	var r := SimRace.new()
	r.level = SimLevel.derive(base, all_items)
	r.tracks = schedule_balls(r.level)
	r.p = SimPlayer.spawn(r.level)
	for g in roster:
		var lvl_g := SimLevel.derive(base, SimLevel.items_upto(all_items, g.round))
		var st := resim(g.inputs, lvl_g)
		r.ghost_streams.append(st)
		var newer: Array = []
		for it in all_items:
			if it.round > g.round and SimLevel.DEFS[it.type].hazard:
				newer.append(it)
		var death := compute_fate(st, newer, r.tracks, g.round)
		r.fates.append({ "death": death, "done": death if death >= 0 else st.len })
	return r

static func schedule_balls(lvl: SimLevel) -> Array:
	var out: Array = []
	for it in lvl.items:
		if it.type != "launcher":
			continue
		var dir := 1 if it.rot == 0 else -1
		var cx: int = it.cx + (1 if dir > 0 else 0)
		var d := 0
		while not lvl.solid_at(cx, it.cy) and d < SimC.GW:
			cx += dir
			d += 1
		var travel := d * SimC.FP + (SimC.FP * 6) / 10
		var life := (travel + SimC.BALL_V - 1) / SimC.BALL_V
		var t0 := SimC.BALL_FIRST
		while t0 < SimC.ROUND_TICKS:
			out.append({ "t0": t0, "life": life,
				"x0": it.cx * SimC.FP + SimC.FP / 2, "y": it.cy * SimC.FP + SimC.FP / 2,
				"dir": dir, "round": it.round })
			t0 += SimC.BALL_EVERY
	return out

static func balls_at(tracks_in: Array, t: int) -> Array:
	var out: Array = []
	for tr in tracks_in:
		var dt: int = t - tr.t0
		if dt < 0 or dt >= tr.life:
			continue
		var x: int = tr.x0 + tr.dir * SimC.BALL_V * dt
		out.append({ "x0": x - SimC.BALL_HW, "x1": x + SimC.BALL_HW,
			"y0": tr.y - SimC.BALL_HH, "y1": tr.y + SimC.BALL_HH,
			"xc": x, "yc": tr.y, "dir": tr.dir, "round": tr.round })
	return out

static func resim(log_bytes: PackedByteArray, lvl: SimLevel) -> Dictionary:
	var tr := schedule_balls(lvl)
	var pl := SimPlayer.spawn(lvl)
	var cd := {}
	var ev: Array = []
	var xs := PackedInt64Array()
	var ys := PackedInt64Array()
	var faces := PackedInt32Array()
	for t in range(log_bytes.size()):
		pl.step(lvl, balls_at(tr, t), cd, log_bytes[t], t, ev)
		xs.append(pl.px)
		ys.append(pl.py)
		faces.append(pl.face)
		if pl.dead or pl.finished:
			break
	return { "xs": xs, "ys": ys, "faces": faces, "len": xs.size(), "finished": pl.finished }

static func compute_fate(st: Dictionary, newer_items: Array, all_tracks: Array, g_round: int) -> int:
	var newer_tracks: Array = []
	for tr in all_tracks:
		if tr.round > g_round:
			newer_tracks.append(tr)
	for t in range(st.len):
		var x: int = st.xs[t]
		var y: int = st.ys[t]
		var bx0 := x - SimC.HW
		var bx1 := x + SimC.HW
		var by0 := y - SimC.PH
		var by1 := y
		for it in newer_items:
			if it.type == "cactus":
				var b: Dictionary = SimLevel.cactus_box(it)
				if bx0 < b.x1 and bx1 > b.x0 and by0 < b.y1 and by1 > b.y0:
					return t
			elif it.type == "fan":
				var cx: int = it.cx * SimC.FP + SimC.FP / 2
				var cy: int = it.cy * SimC.FP + SimC.FP / 2
				var qx := clampi(cx, bx0, bx1)
				var qy := clampi(cy, by0, by1)
				if (cx - qx) * (cx - qx) + (cy - qy) * (cy - qy) < SimC.FAN_R2:
					return t
		for a in balls_at(newer_tracks, t):
			if bx0 < a.x1 and bx1 > a.x0 and by0 < a.y1 and by1 > a.y0:
				return t
	return -1

func step(b: int) -> void:
	var alive := not (p.dead or p.finished)
	if alive:
		inputs.append(b)
		p.step(level, balls_at(tracks, tick), cushion_last, b, tick, events)
	for i in range(fates.size()):
		var f: Dictionary = fates[i]
		if f.death == tick:
			var st: Dictionary = ghost_streams[i]
			events.append({ "t": "swat", "i": i, "x": st.xs[f.death], "y": st.ys[f.death] })
		elif f.death < 0 and tick == st_len(i):
			events.append({ "t": "gfinish", "i": i })
	tick += 1
	if not p.dead and not p.finished and tick >= SimC.ROUND_TICKS:
		events.append({ "t": "time", "x": p.px, "y": p.py })
		p.dead = true
		p.done_tick = tick

func st_len(i: int) -> int:
	return ghost_streams[i].len

func player_done() -> bool:
	return p.dead or p.finished

func ghosts_done() -> bool:
	for f in fates:
		if tick < f.done:
			return false
	return true

func resolved() -> bool:
	if not player_done() or not ghosts_done():
		return false
	var last: int = maxi(p.done_tick, 0)
	for f in fates:
		last = maxi(last, f.done)
	return tick - last > RESOLVE_BEAT

func checksum() -> int:
	var h := SimC.fnv_seed()
	h = SimC.fnv_int(h, tick)
	h = SimC.fnv_int(h, p.px)
	h = SimC.fnv_int(h, p.py)
	h = SimC.fnv_int(h, p.vx)
	h = SimC.fnv_int(h, p.vy)
	h = SimC.fnv_int(h, p.coyote)
	h = SimC.fnv_int(h, p.buffer)
	h = SimC.fnv_int(h, p.wallc)
	h = SimC.fnv_int(h, p.drop)
	var flags := 0
	if p.grounded: flags |= 1
	if p.dead: flags |= 2
	if p.finished: flags |= 4
	if p.jump_prev: flags |= 8
	if p.down_prev: flags |= 16
	h = SimC.fnv_int(h, flags * p.face)
	for i in range(level.items.size()):
		h = SimC.fnv_int(h, int(cushion_last.get(i, -999)))
	return h
